CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" accelerate launch \
	--multi_gpu \
	--num_machines="1" \
	--num_processes="1" \
	--mixed_precision="fp16" \
	--num_cpu_threads_per_process="12" \
	run.py \
		--train_datasets \ 
			data/train_clean_1_1000.tsv \
			data/train_clean_2_1000.tsv \
			data/train_clean_3_1000.tsv \ 
   			data/train_clean_4_1000.tsv \ 
      			data/train_clean_5_1000.tsv \ 
	 		data/train_clean_6_1000.tsv \ 
    			data/train_clean_7_1000.tsv \ 
       			data/train_clean_8_1000.tsv \ 
	  		data/train_clean_9_1000.tsv \ 
     			data/train_clean_10_1000.tsv \ 
		--val_datasets \
			data/dev_clean.tsv \
		--audio_column_name="path" \
		--duration_column_name="duration" \
		--separator="\t" \
		--model_name_or_path="nguyenvulebinh/wav2vec2-base-vi" \
		--load_from_pretrained \
		--output_dir="wav2vec2_pretraining" \
		--max_train_steps="300000" \
		--num_warmup_steps="90000" \
		--gradient_accumulation_steps="8" \
		--learning_rate="0.005" \
		--weight_decay="0.01" \
		--max_duration_in_seconds="15.6" \
		--min_duration_in_seconds="0.5" \
		--logging_steps="1" \
		--saving_steps="100" \
		--per_device_train_batch_size="16" \
		--per_device_eval_batch_size="8" \
		--adam_beta1="0.9" \
		--adam_beta2="0.98" \
		--adam_epsilon="1e-06" \
		--gradient_checkpointing

